name: CI
on: [push]

jobs:
  updateindex:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: Test with Gradle
        run: cd indexer && ./gradlew clean test -i