name: CI
on:
  workflow_dispatch:
  schedule:
    - cron: '*/15 * * * *'

jobs:
  updateindex:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: Test with Gradle
        run: cd indexer && ./gradlew clean test -i
      - name: Commit db changes
        run: git config user.email "github-action@example.com" && git config user.name "Github Action" && git add docs/mydatabase.db && git commit --message="update index" && git push origin main